### ISSUE TITLE
Improve File action syntax

### ISSUE THREAD

**Issue by ashur** [ashur/fig#12]
The current syntax for File actions overloads the method property to signify both:

* The type of file action to perform — ex., `create`, `delete`
* The path to the file on disk

For example:
```
- name: create empty file
  file:
      create: ~/Desktop/empty.txt
```

While concise, it is also imprecise and does not match the parallel Defaults action syntax:

```
- name: write Foo=Bar
  defaults:
      action: write
      domain: com.example.Newton
      key: Foo
      value: Bar
```

## Desired Syntax
Instead, consider explicitly declaring the desired action type via a new `action` property, and specifying the file path using a new `path` property:

```
- name: create file
  file:
      action: create
      path: ~/Desktop/hello.txt
      contents: "hello, world."

- name: replace file
  file:
      action: replace
      path: ~/Desktop/hello.txt
      source: hello.txt

- name: delete file
  file:
      action: delete
      path: ~/Desktop/hello.txt
```
