### ISSUE TITLE
Variable replacement not performed on ‘defaults:write’ result output

### ISSUE THREAD

**Issue by ashur** [ashur/fig#21]
## Steps

Deploy a profile which contains the following:

```yaml
- vars:
    defaults_value: ABCD-EFGH-IJKL-MNOP

- name: defaults-action
  defaults:
      action: write
      domain: com.example.Newton
      key: SerialNumber
      value: "{{ defaults_value }}”
```

## Expected

The following will be output:

```
DEFAULTS: write | com.example.Newton SerialNumber ******************************
ABCD-EFGH-IJKL-MNOP
```

## Actual

The following is output:

```
DEFAULTS: write | com.example.Newton SerialNumber ******************************
{{ defaults_value }}
```

## Notes

Variable replacement _is_ performed when writing the defaults value, just not when generating the output string.
