### ISSUE TITLE
file.replace: Asset fallback

### ISSUE THREAD

**Issue by ashur** [ashur/fig#23]
## Summary

Rather than require each `extend`-ing profile to bring all of its own assets, Fig should support asset fallback: if a child profile does not have a given asset but a profile further up the inheritance chain does, the parent profile's asset should be used instead.

This would allow for less asset duplication, an overall improvement.

## Configuration

Two profiles, `foo/.base` and `foo/demo`:

**.base.yml**

```yml
# .base
---

- name: config
  file:
      action: replace
      path: ~/.atom/config.cson
      source: config.cson

- name: keymap
  file:
      action: replace
      path: ~/.atom/keymap.cson
      source: keymap.cson
```

**demo.yml**

```yml
# demo

- extend: .base
```

and the following assets structure:

```
+ assets/
  |
  + .base/
  | |
  | + config.cson
  | + keymap.cson
  |
  + demo/
    |
    + config.cson
```

## Current Behavior

Deploying `foo/demo` causes an error:

```
FILE: replace | config *********************************************************
Source missing: '~/.fig/atom/assets/demo/keymap.cson'
```

## Suggested Behavior

Fig should work up through the profile chain looking for the next-closest asset match. In our example, deploying `foo/demo` would use the following assets:

- `assets/demo/config.cson`
- `assets/.base/keymap.cson`
