### ISSUE TITLE
defaults.write: ignore_output is ignored

### ISSUE THREAD

**Issue by ashur** [ashur/fig#26]
## Steps

Deploy a profile which contains the following:

```yaml
- name: defaults-action
  defaults:
      action: write
      domain: com.example.Newton
      key: SerialNumber
      value: ABCD-EFGH-IJKL-MNOP
  ignore_output: true
```

## Expected

The following will be output:

```
DEFAULTS: write | com.example.Newton SerialNumber ******************************
OK
```

## Actual

The following is output:

```
DEFAULTS: write | com.example.Newton SerialNumber ******************************
ABCD-EFGH-IJKL-MNOP
```
