### ISSUE TITLE
vars defined in `include`-d profile missing from including profile's actions

### ISSUE THREAD

**Issue by ashur** [ashur/fig#27]
## Steps

Given two profiles:

**global-vars.yml**
```yaml
# global-vars
---

- vars:
    greeting: Hello

- name: "[DEBUG] The Greeting"
  command: "echo 'greeting: {{ greeting }}'"
```

**hello.yml**

```yaml
# hello
---

- include: global-vars

- vars:
    who: Dolly

- name: Say Hello
  command: "echo '{{ greeting }}, {{ who }}.'"
```

Deploy **hello**

## Expected

Variables defined in `global-vars` will be substituted in actions defined in that profile _and_ in actions defined in the including profile `hello`:

```
$ fig deploy example/hello

COMMAND: [DEBUG] The Greeting **************************************************
greeting: Hello

COMMAND: Say Hello *************************************************************
Hello, Dolly.
```

## Actual

Variables defined in `global-vars` are only substituted in actions defined in that profile:

```
$ fig deploy example/hello

COMMAND: [DEBUG] The Greeting **************************************************
greeting: Hello

COMMAND: Say Hello *************************************************************
{{ greeting }}, Dolly.
```
