### ISSUE TITLE
Snapshotting does not perform variable replacement on target path

### ISSUE THREAD

**Issue by ashur** [ashur/fig#29]
## Steps

Given the following profile **replace-foo**:

```yaml
# replace-foo

- vars:
    folder: Desktop

- name: replace file
  file:
      action: replace
      path: ~/{{ folder }}/foo.txt
      source: foo.txt
```

and an existing file `~/Desktop/foo.txt`, snapshot **replace-foo**

## Expected

Fig will copy `~/Desktop/foo.txt` to **replace-foo**’s assets folder

## Actual

Nothing happens, because variable replacement is not being performed on the value of `path`
