### ISSUE TITLE
Support for defining variables on the command line

### ISSUE THREAD

**Issue by ashur** [ashur/fig#4]
## Format

The following declaration types should be supported:

* `--foo`, sets `foo` to `true`
* `--foo=bar`, sets `foo` to `bar`

## Precedence

If a profile `newton/hello` is defined as:

```
# hello
---

vars:
    who: world

- name: say hello
  command: echo "hello, {{ who }}."
```

would behave as follows:

```
$ fig deploy newton/hello
hello, world.
```

A variable scoped at the command line would take precedence over any variable defined in the profile itself:
```
$ fig deploy newton/profile --who=Dolly
hello, Dolly.
```
